### ISSUE TITLE
Contact info

### ISSUE THREAD

**Issue by joshmhanson** [ossu/code-of-conduct#2]
It currently lists our gitter usernames. Are we able to directly link to people on Discord?

**Comment by waciumawanjohi** [comment]
We might be able to. Do we need to have individual contact information there? I wonder if we should just put an email link. Or tell folks to @ moderators in the Discord rules channel once it's created.

**Comment by joshmhanson** [comment]
> I wonder if we should just put an email link.

Yeah I think that's a better idea, maybe we could setup an official email address like moderation-team@ossu.dev for reporting code of conduct violations?
